import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../globals.css';
import { ThemeProvider } from '@/components/theme-provider';
import NextTopLoader from '@/components/progressbar-provider';
import ToastProvider from '@/components/toast-provider';
import Sidebar from '@/components/me/navigation/Sidebar';
import Navbar from '@/components/me/navigation/Navbar';
import { auth } from '@/auth';
import AuthProvider from '@/components/auth-provider';
import FlyoutMenu from '@/components/me/navigation/FlyoutMenu';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: {
    template: '%s | Aku - Oliku',
    default: 'Aku - Oliku', // a default is required when creating a template
  },
  description: 'Generated by create next app',
  icons: {
    icon: '/assets/favicon.ico',
    shortcut: '/assets/shortcut-icon.png',
    apple: '/assets/apple-icon.png',
    other: {
      rel: 'apple-touch-icon-precomposed',
      url: '/assets/apple-touch-icon-precomposed.png',
    },
  },
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={inter.className}>
        <AuthProvider session={session}>
          <ThemeProvider
            attribute='class'
            defaultTheme='system'
            enableSystem
            disableTransitionOnChange
          >
            <NextTopLoader />
            <ToastProvider />
            <Navbar />
            <FlyoutMenu />
            <main className='container mt-20 py-10 pb-32'>{children}</main>
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
